export type Model = {
  id: string;
  label: string;
  description: string;
};

export type Category = {
  name: string;
  defaultInput: string;
  models: Model[];
};

export const MODEL_CATALOG: Record<string, Category> = {
  image: {
    name: "Image Generation",
    defaultInput: '{\n  "prompt": "a cat astronaut riding a bicycle on mars"\n}',
    models: [
      { id: "black-forest-labs/flux-2-pro", label: "FLUX 2 Pro", description: "High-quality generation and editing with eight reference images" },
      { id: "black-forest-labs/flux-2-flex", label: "FLUX 2 Flex", description: "Max-quality generation and editing with ten reference images" },
      { id: "black-forest-labs/flux-2-max", label: "FLUX 2 Max", description: "Highest fidelity image model from Black Forest Labs" },
      { id: "black-forest-labs/flux-1.1-pro", label: "FLUX 1.1 Pro", description: "Faster, better FLUX Pro with excellent prompt adherence" },
      { id: "black-forest-labs/flux-1.1-pro-ultra", label: "FLUX 1.1 Pro Ultra", description: "FLUX 1.1 in ultra and raw modes up to 4MP" },
      { id: "black-forest-labs/flux-pro", label: "FLUX Pro", description: "State-of-the-art with top prompt following and detail" },
      { id: "prunaai/flux-fast", label: "FLUX Fast", description: "Fastest Flux endpoint available" },
      { id: "black-forest-labs/flux-fill-pro", label: "FLUX Fill Pro", description: "Professional inpainting and outpainting" },
      { id: "black-forest-labs/flux-2-klein-4b", label: "FLUX 2 Klein 4B", description: "Very fast generation and editing model" },
      { id: "black-forest-labs/flux-2-klein-9b", label: "FLUX 2 Klein 9B", description: "4-step distilled version for maximum flexibility" },
      { id: "black-forest-labs/flux-kontext-pro", label: "FLUX Kontext Pro", description: "State-of-the-art text-based image editing" },
      { id: "black-forest-labs/flux-kontext-max", label: "FLUX Kontext Max", description: "Premium text-based editing with maximum performance" },
      { id: "google/imagen-4", label: "Imagen 4", description: "Google's flagship image generation model" },
      { id: "google/imagen-4-ultra", label: "Imagen 4 Ultra", description: "Ultra version when quality matters most" },
      { id: "google/imagen-4-fast", label: "Imagen 4 Fast", description: "Fast version when speed and cost are priorities" },
      { id: "google/imagen-3", label: "Imagen 3", description: "Highest quality text-to-image with rich detail" },
      { id: "google/imagen-3-fast", label: "Imagen 3 Fast", description: "Faster and cheaper, prioritizing speed" },
      { id: "google/nano-banana-2", label: "Nano Banana 2", description: "Fast generation with conversational editing" },
      { id: "google/nano-banana-pro", label: "Nano Banana Pro", description: "SOTA generation and editing model" },
      { id: "openai/gpt-image-1.5", label: "GPT Image 1.5", description: "Latest with better instruction following" },
      { id: "openai/gpt-image-1-mini", label: "GPT Image 1 Mini", description: "Cost-efficient version of GPT Image 1" },
      { id: "openai/dall-e-3", label: "DALL-E 3", description: "Realistic images from natural language" },
      { id: "openai/dall-e-2", label: "DALL-E 2", description: "The classic DALL-E 2" },
      { id: "xai/grok-imagine-image", label: "Grok Imagine Image", description: "SOTA image model from xAI" },
      { id: "qwen/qwen-image", label: "Qwen Image", description: "Advanced text rendering in image generation" },
      { id: "qwen/qwen-image-2", label: "Qwen Image 2", description: "Next-gen with strong text rendering" },
      { id: "qwen/qwen-image-2-pro", label: "Qwen Image 2 Pro", description: "Pro version with enhanced realism" },
      { id: "ideogram-ai/ideogram-v3-turbo", label: "Ideogram V3 Turbo", description: "Fastest and cheapest Ideogram v3" },
      { id: "ideogram-ai/ideogram-v3-balanced", label: "Ideogram V3 Balanced", description: "Balance speed, quality, and cost" },
      { id: "ideogram-ai/ideogram-v3-quality", label: "Ideogram V3 Quality", description: "Highest quality Ideogram v3" },
      { id: "ideogram-ai/ideogram-v2", label: "Ideogram V2", description: "Excellent with state-of-the-art inpainting" },
      { id: "ideogram-ai/ideogram-character", label: "Ideogram Character", description: "Consistent characters from reference images" },
      { id: "recraft-ai/recraft-v4", label: "Recraft V4", description: "Built around design taste" },
      { id: "recraft-ai/recraft-v4-pro", label: "Recraft V4 Pro", description: "~2048px resolution with higher fidelity" },
      { id: "recraft-ai/recraft-v3", label: "Recraft V3", description: "SOTA generation with long text capability" },
      { id: "recraft-ai/recraft-20b", label: "Recraft 20B", description: "Affordable and fast image generation" },
      { id: "prunaai/p-image", label: "P-Image", description: "Sub-1-second text-to-image for production" },
      { id: "prunaai/p-image-edit", label: "P-Image Edit", description: "Multi-image editing for production" },
      { id: "prunaai/z-image-turbo", label: "Z-Image Turbo", description: "Super fast 6B parameter model" },
      { id: "bria/image-3.2", label: "Bria Image 3.2", description: "Commercial-ready trained on licensed data" },
      { id: "bytedance/seedream-4.5", label: "Seedream 4.5", description: "Stronger spatial understanding" },
      { id: "bytedance/seedream-5-lite", label: "Seedream 5 Lite", description: "Built-in reasoning and editing" },
      { id: "bytedance/seedream-4", label: "Seedream 4", description: "Unified generation and single-sentence editing" },
      { id: "bytedance/seedream-3", label: "Seedream 3", description: "2K native text-to-image support" },
      { id: "bytedance/dreamina-3.1", label: "Dreamina 3.1", description: "4MP text-to-image with cinematic quality" },
      { id: "leonardoai/phoenix-1.0", label: "Phoenix 1.0", description: "Foundational model producing up to 5MP" },
      { id: "leonardoai/lucid-origin", label: "Lucid Origin", description: "Artistic visuals with improved prompt adherence" },
      { id: "reve/create", label: "Reve Create", description: "Image generation from Reve" },
      { id: "reve/edit", label: "Reve Edit", description: "Image editing from Reve" },
      { id: "reve/remix", label: "Reve Remix", description: "Multiple reference image handling" },
      { id: "sourceful/riverflow-2.0-pro", label: "Riverflow 2.0 Pro", description: "Agentic model for high-precision" },
      { id: "sourceful/riverflow-2.0-fast", label: "Riverflow 2.0 Fast", description: "Agentic model for fast generation" },
      { id: "retro-diffusion/rd-plus", label: "RD Plus", description: "High quality pixel art generation" },
      { id: "retro-diffusion/rd-fast", label: "RD Fast", description: "Fast pixel art generation" },
    ],
  },
  imageTools: {
    name: "Image Tools",
    defaultInput: '{\n  "image": "https://example.com/image.jpg"\n}',
    models: [
      { id: "google/upscaler", label: "Google Upscaler", description: "Upscale images 2x or 4x" },
      { id: "recraft-ai/recraft-remove-background", label: "Recraft Remove BG", description: "Automated background removal" },
      { id: "recraft-ai/recraft-crisp-upscale", label: "Recraft Crisp Upscale", description: "Enhance sharpness for web or print" },
      { id: "recraft-ai/recraft-creative-upscale", label: "Recraft Creative Upscale", description: "Enhance details and refine elements" },
      { id: "recraft-ai/recraft-vectorize", label: "Recraft Vectorize", description: "Convert raster images to SVG" },
      { id: "recraft-ai/recraft-v4-svg", label: "Recraft V4 SVG", description: "Production-ready SVG from text" },
      { id: "recraft-ai/recraft-v3-svg", label: "Recraft V3 SVG", description: "High quality SVG including logos" },
      { id: "bria/eraser", label: "Bria Eraser", description: "SOTA object removal" },
      { id: "bria/remove-background", label: "Bria Remove BG", description: "Background removal" },
      { id: "bria/genfill", label: "Bria GenFill", description: "Object addition or visual transformation" },
      { id: "bria/generate-background", label: "Bria Generate BG", description: "Background swapping via text or reference" },
      { id: "bria/increase-resolution", label: "Bria Increase Resolution", description: "Upscaling preserving original content" },
      { id: "bria/expand-image", label: "Bria Expand", description: "Expand images beyond borders" },
      { id: "bria/fibo", label: "Bria FIBO", description: "Structured control for precise generation" },
      { id: "topazlabs/image-colorization", label: "Image Colorization", description: "Colorize images from Topaz Labs" },
      { id: "topazlabs/dust-and-scratch-v2", label: "Dust & Scratch V2", description: "Remove dust and scratches from old photos" },
      { id: "philz1337x/crystal-upscaler", label: "Crystal Upscaler", description: "High-precision upscaler for portraits" },
      { id: "qwen/qwen-image-edit-2511", label: "Qwen Image Edit", description: "Enhanced editing with better consistency" },
    ],
  },
  kontextApps: {
    name: "Kontext Apps",
    defaultInput: '{\n  "prompt": "turn this into a cartoon",\n  "image_url": "https://example.com/photo.jpg"\n}',
    models: [
      { id: "flux-kontext-apps/multi-image-kontext-max", label: "Multi-Image Kontext Max", description: "Combine two images experimentally" },
      { id: "flux-kontext-apps/multi-image-kontext-pro", label: "Multi-Image Kontext Pro", description: "Combine images with FLUX Kontext Pro" },
      { id: "flux-kontext-apps/face-to-many-kontext", label: "Face to Many", description: "Become a character, in style" },
      { id: "flux-kontext-apps/change-haircut", label: "Change Haircut", description: "Change hairstyle and hair color" },
      { id: "flux-kontext-apps/professional-headshot", label: "Professional Headshot", description: "Create professional headshot from any image" },
      { id: "flux-kontext-apps/restore-image", label: "Restore Image", description: "Restore photos, fix scratches, colorize" },
      { id: "flux-kontext-apps/text-removal", label: "Text Removal", description: "Remove all text from an image" },
      { id: "flux-kontext-apps/portrait-series", label: "Portrait Series", description: "Portrait photo series from single image" },
      { id: "flux-kontext-apps/depth-of-field", label: "Depth of Field", description: "Bring subjects into focus" },
      { id: "flux-kontext-apps/cartoonify", label: "Cartoonify", description: "Turn image into a cartoon" },
      { id: "flux-kontext-apps/filters", label: "Filters", description: "Add simple filters to images" },
      { id: "flux-kontext-apps/impossible-scenarios", label: "Impossible Scenarios", description: "Impossible adventures from a single image" },
      { id: "flux-kontext-apps/iconic-locations", label: "Iconic Locations", description: "Place yourself in iconic world locations" },
    ],
  },
  video: {
    name: "Video Generation",
    defaultInput: '{\n  "prompt": "a golden retriever running on a beach at sunset"\n}',
    models: [
      { id: "google/veo-3.1", label: "VEO 3.1", description: "Higher-fidelity with reference support" },
      { id: "google/veo-3.1-fast", label: "VEO 3.1 Fast", description: "Faster VEO 3 with context-aware audio" },
      { id: "google/veo-3", label: "VEO 3", description: "Flagship text-to-video with audio" },
      { id: "google/veo-3-fast", label: "VEO 3 Fast", description: "Faster and cheaper with audio" },
      { id: "google/veo-2", label: "VEO 2", description: "State-of-the-art video generation" },
      { id: "openai/sora-2-pro", label: "Sora 2 Pro", description: "Most advanced synced-audio video" },
      { id: "openai/sora-2", label: "Sora 2", description: "Flagship video with synced audio" },
      { id: "xai/grok-imagine-video", label: "Grok Imagine Video", description: "xAI's video generation model" },
      { id: "xai/grok-imagine-r2v", label: "Grok Imagine R2V", description: "Videos guided by reference images" },
      { id: "runwayml/gen-4.5", label: "Gen-4.5", description: "SOTA motion quality and visual fidelity" },
      { id: "bytedance/seedance-1.5-pro", label: "Seedance 1.5 Pro", description: "Joint audio-video with complex instructions" },
      { id: "bytedance/seedance-1-pro", label: "Seedance 1 Pro", description: "Text-to-video and image-to-video" },
      { id: "bytedance/seedance-1-lite", label: "Seedance 1 Lite", description: "Video generation at 480p and 720p" },
      { id: "bytedance/omni-human-1.5", label: "Omni Human 1.5", description: "Film-grade digital human from image + audio" },
      { id: "bytedance/dreamactor-m2.0", label: "DreamActor M2.0", description: "Animate characters from single image" },
      { id: "kwaivgi/kling-v3-video", label: "Kling V3 Video", description: "Cinematic videos up to 15s with multi-shot" },
      { id: "kwaivgi/kling-v3-omni-video", label: "Kling V3 Omni", description: "Unified multimodal video with audio" },
      { id: "kwaivgi/kling-v2.6", label: "Kling V2.6 Pro", description: "Top-tier image-to-video with cinematic visuals" },
      { id: "kwaivgi/kling-v2.1-master", label: "Kling V2.1 Master", description: "Premium dynamics and prompt adherence" },
      { id: "kwaivgi/kling-v2.1", label: "Kling V2.1", description: "Image-to-video at 720p and 1080p" },
      { id: "vidu/q3-pro", label: "VIDU Q3 Pro", description: "High-fidelity up to 16s at 1080p" },
      { id: "vidu/q3-turbo", label: "VIDU Q3 Turbo", description: "Fast video up to 16s at 1080p" },
      { id: "pixverse/pixverse-v5.6", label: "Pixverse V5.6", description: "Astonishing physics simulation" },
      { id: "pixverse/pixverse-v5", label: "Pixverse V5", description: "Enhanced movement and visual effects" },
      { id: "pixverse/pixverse-v4.5", label: "Pixverse V4.5", description: "Enhanced motion and prompt coherence" },
      { id: "lightricks/ltx-2.3-pro", label: "LTX-2.3 Pro", description: "High-fidelity with portrait support and 4K" },
      { id: "lightricks/ltx-2.3-fast", label: "LTX-2.3 Fast", description: "Lightning-fast with portrait support" },
      { id: "lightricks/ltx-2-pro", label: "LTX-2 Pro", description: "High visual fidelity for content creation" },
      { id: "lightricks/audio-to-video", label: "LTX Audio-to-Video", description: "Audio + image/prompt to video" },
      { id: "wan-video/wan2.6-i2v-flash", label: "WAN 2.6 I2V Flash", description: "Image-to-video with optional audio" },
      { id: "wan-video/wan-2.6-t2v", label: "WAN 2.6 T2V", description: "Alibaba text-to-video generation" },
      { id: "wan-video/wan-2.5-i2v", label: "WAN 2.5 I2V", description: "Image-to-video with background audio" },
      { id: "wan-video/wan-2.5-t2v", label: "WAN 2.5 T2V", description: "Text-to-video generation" },
      { id: "prunaai/p-video", label: "P-Video", description: "Fast video with draft mode for iteration" },
      { id: "minimax/video-01", label: "MiniMax Video 01", description: "Video creation and synthesis" },
      { id: "leonardoai/motion-2.0", label: "Motion 2.0", description: "5s 480p videos from text prompt" },
    ],
  },
  videoTools: {
    name: "Video Tools",
    defaultInput: '{\n  "video_url": "https://example.com/video.mp4"\n}',
    models: [
      { id: "kwaivgi/kling-v3-motion-control", label: "Kling V3 Motion Control", description: "Transfer motion from video to character" },
      { id: "kwaivgi/kling-o1", label: "Kling O1", description: "Modify videos through natural language" },
      { id: "kwaivgi/kling-avatar-v2", label: "Kling Avatar V2", description: "Avatar videos with realistic characters" },
      { id: "kwaivgi/kling-lip-sync", label: "Kling Lip Sync", description: "Add lip-sync with audio or text" },
      { id: "pixverse/lipsync", label: "Pixverse Lipsync", description: "Realistic lipsync from audio" },
      { id: "lightricks/ltx-2-retake", label: "LTX-2 Retake", description: "Edit specific sections of videos" },
      { id: "sync/lipsync-2", label: "Sync Lipsync 2", description: "Generate realistic lipsyncs" },
      { id: "sync/lipsync-2-pro", label: "Sync Lipsync 2 Pro", description: "Studio-grade lipsync in minutes" },
      { id: "sync/react-1", label: "Sync React 1", description: "Lipsync with refined emotion" },
      { id: "heygen/video-agent", label: "HeyGen Video Agent", description: "Text prompt to polished video" },
      { id: "heygen/video-translate", label: "HeyGen Video Translate", description: "Translate videos into 150+ languages" },
      { id: "heygen/avatar-iv", label: "HeyGen Avatar IV", description: "Realistic talking avatar from text" },
      { id: "veed/fabric-1.0", label: "VEED Fabric 1.0", description: "Turn images into talking videos" },
      { id: "bria/video-remove-background", label: "Bria Video Remove BG", description: "Remove backgrounds from videos" },
      { id: "bria/video-increase-resolution", label: "Bria Video Upscale", description: "Upscale videos up to 8K" },
      { id: "bria/video-erase-object", label: "Bria Video Erase", description: "Object removal from videos" },
      { id: "philz1337x/crystal-video-upscaler", label: "Crystal Video Upscaler", description: "High-precision video upscaler" },
      { id: "mirelo/video-to-sfx-v1.5", label: "Video-to-SFX V1.5", description: "Generate synced sounds for video" },
      { id: "xai/grok-imagine-video-extension", label: "Grok Video Extension", description: "Extend videos describing what happens next" },
      { id: "wan-video/wan-2.2-animate-replace", label: "WAN Animate Replace", description: "Replace a character in a video scene" },
    ],
  },
  audio: {
    name: "Audio & Speech",
    defaultInput: '{\n  "prompt": "lo-fi ambient chill beats"\n}',
    models: [
      { id: "minimax/music-2.5", label: "Music 2.5", description: "Full-length songs with vocals and instrumentation" },
      { id: "google/lyria-2", label: "Lyria 2", description: "Music generation producing 48kHz stereo" },
      { id: "minimax/speech-2.8-turbo", label: "Speech 2.8 Turbo", description: "Natural speech with voice cloning" },
      { id: "minimax/speech-2.8-hd", label: "Speech 2.8 HD", description: "High-fidelity with emotion control" },
      { id: "inworld/tts-1.5-mini", label: "TTS 1.5 Mini", description: "Ultra-fast TTS with ~120ms latency" },
      { id: "inworld/tts-1.5-max", label: "TTS 1.5 Max", description: "Highest-quality TTS under 200ms" },
      { id: "qwen/qwen3-tts", label: "Qwen3 TTS", description: "Unified TTS with three powerful modes" },
      { id: "resemble-ai/chatterbox-turbo", label: "Chatterbox Turbo", description: "Fastest open source TTS" },
    ],
  },
  language: {
    name: "Language Models",
    defaultInput: '{\n  "prompt": "Explain quantum computing in simple terms"\n}',
    models: [
      { id: "openai/gpt-5.4", label: "GPT-5.4", description: "Most capable frontier model" },
      { id: "openai/gpt-5.2", label: "GPT-5.2", description: "Best for coding and agentic tasks" },
      { id: "openai/gpt-5", label: "GPT-5", description: "Excelling at coding, writing, reasoning" },
      { id: "openai/gpt-5-mini", label: "GPT-5 Mini", description: "Faster version of flagship GPT-5" },
      { id: "openai/gpt-5-nano", label: "GPT-5 Nano", description: "Fastest, most cost-effective GPT-5" },
      { id: "openai/gpt-4o", label: "GPT-4o", description: "High-intelligence chat model" },
      { id: "openai/gpt-4.1", label: "GPT-4.1", description: "Flagship GPT for complex tasks" },
      { id: "openai/gpt-4.1-mini", label: "GPT-4.1 Mini", description: "Fast, affordable GPT-4.1" },
      { id: "openai/o1", label: "O1", description: "First o-series reasoning model" },
      { id: "openai/o4-mini", label: "O4 Mini", description: "Fast, lightweight reasoning" },
      { id: "deepseek-ai/deepseek-v3.1", label: "DeepSeek V3.1", description: "Latest hybrid thinking model" },
      { id: "deepseek-ai/deepseek-v3", label: "DeepSeek V3", description: "Leading non-reasoning open source model" },
      { id: "deepseek-ai/deepseek-r1", label: "DeepSeek R1", description: "Reasoning with reinforcement learning" },
      { id: "xai/grok-4", label: "Grok 4", description: "xAI's most advanced reasoning model" },
      { id: "moonshotai/kimi-k2-thinking", label: "Kimi K2 Thinking", description: "Latest, most capable thinking model" },
      { id: "moonshotai/kimi-k2.5", label: "Kimi K2.5", description: "Unified vision and text, thinking and non-thinking" },
      { id: "google/gemini-3.1-pro", label: "Gemini 3.1 Pro", description: "Most intelligent with improved reasoning" },
      { id: "google/gemini-3-pro", label: "Gemini 3 Pro", description: "Most advanced reasoning Gemini" },
      { id: "google/gemini-3-flash", label: "Gemini 3 Flash", description: "Most intelligent built for speed" },
      { id: "google/gemini-2.5-flash", label: "Gemini 2.5 Flash", description: "Hybrid thinking optimized for speed" },
      { id: "meta/llama-4-maverick-instruct", label: "Llama 4 Maverick", description: "17B param model with 128 experts" },
      { id: "meta/llama-4-scout-instruct", label: "Llama 4 Scout", description: "17B param model with 16 experts" },
      { id: "anthropic/claude-opus-4.6", label: "Claude Opus 4.6", description: "Most intelligent with SOTA coding" },
      { id: "ibm-granite/granite-4.0-h-small", label: "Granite 4.0 H Small", description: "32B long-context instruct model" },
    ],
  },
  threeD: {
    name: "3D",
    defaultInput: '{\n  "image": "https://example.com/object.jpg"\n}',
    models: [
      { id: "hyper3d/rodin", label: "Rodin", description: "Generate complex 3D models from images" },
      { id: "tencent/hunyuan-3d-3.1", label: "HunYuan 3D 3.1", description: "3D models with texture fidelity and geometry" },
    ],
  },
};
